export const batch1 = [
    {
        "regularizationRequestsId": 11345,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2024-01-30"
        ],
        "appliedOnDate": "2024-01-31 16:35:15.462",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "30-01-2024 10:34",
        "checkOutTime": "30-01-2024 19:38",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2024-02-02T10:48:53.934+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 11469,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2024-01-22"
        ],
        "appliedOnDate": "2024-02-02 14:16:30.84",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "22-01-2024 10:15",
        "checkOutTime": "22-01-2024 19:22",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2024-02-05T10:55:36.834+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 11344,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2024-01-09"
        ],
        "appliedOnDate": "2024-01-31 16:34:50.312",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "09-01-2024 10:34",
        "checkOutTime": "09-01-2024 19:43",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2024-02-02T10:48:46.33+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 11343,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2024-01-08"
        ],
        "appliedOnDate": "2024-01-31 16:34:29.842",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "08-01-2024 10:34",
        "checkOutTime": "08-01-2024 19:38",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2024-02-02T10:48:50.224+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 11034,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-12-27"
        ],
        "appliedOnDate": "2023-12-31 15:17:21.342",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "27-12-2023 10:17",
        "checkOutTime": "27-12-2023 19:28",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2024-01-02T15:08:59.676+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 11088,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-12-26"
        ],
        "appliedOnDate": "2024-01-03 11:41:07.529",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "26-12-2023 10:23",
        "checkOutTime": "26-12-2023 19:34",
        "regularizationReason": "5",
        "regularizationComments": "Approved",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2024-01-04T12:06:54.513+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 11033,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-12-26"
        ],
        "appliedOnDate": "2023-12-31 15:16:47.621",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "26-12-2023 10:15",
        "checkOutTime": "26-12-2023 15:33",
        "regularizationReason": "5",
        "regularizationComments": "test",
        "regularizationStatus": "CANCELLED",
        "supervisorActionDate": "2024-01-02T15:09:03.097+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 11032,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-12-18"
        ],
        "appliedOnDate": "2023-12-31 15:16:13.777",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "18-12-2023 10:11",
        "checkOutTime": "18-12-2023 19:20",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2024-01-02T15:09:06.532+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 11035,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-12-05"
        ],
        "appliedOnDate": "2023-12-31 15:19:15.46",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "05-12-2023 10:32",
        "checkOutTime": "05-12-2023 19:37",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2024-01-02T15:08:56.436+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 11048,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-12-04"
        ],
        "appliedOnDate": "2024-01-02 11:21:40.976",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "04-12-2023 13:32",
        "checkOutTime": "04-12-2023 19:40",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2024-01-02T15:08:46.58+05:30",
        "isHalfDay": true,
        "dayHalfs": "Second_Half",
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 11049,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-12-04"
        ],
        "appliedOnDate": "2024-01-02 11:21:41.031",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "04-12-2023 13:32",
        "checkOutTime": "04-12-2023 19:40",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2024-01-02T15:08:43.341+05:30",
        "isHalfDay": true,
        "dayHalfs": "Second_Half",
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 10769,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-11-22"
        ],
        "appliedOnDate": "2023-12-04 02:34:50.833",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "22-11-2023 10:12",
        "checkOutTime": "22-11-2023 19:20",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-12-04T11:47:07.182+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 10768,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-11-09"
        ],
        "appliedOnDate": "2023-12-04 02:32:31.557",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "09-11-2023 10:21",
        "checkOutTime": "09-11-2023 19:31",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-12-04T11:47:10.445+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 10767,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-11-07"
        ],
        "appliedOnDate": "2023-12-04 02:29:07.311",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "07-11-2023 10:11",
        "checkOutTime": "07-11-2023 19:30",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-12-04T11:47:03.83+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 10288,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-10-13"
        ],
        "appliedOnDate": "2023-10-31 16:10:58.649",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "13-10-2023 10:10",
        "checkOutTime": "13-10-2023 19:30",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-11-03T11:20:40.865+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 10287,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-10-09"
        ],
        "appliedOnDate": "2023-10-31 16:10:16.761",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "09-10-2023 10:10",
        "checkOutTime": "09-10-2023 19:25",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-11-03T11:20:54.259+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 10286,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-10-06"
        ],
        "appliedOnDate": "2023-10-31 16:09:10.772",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "06-10-2023 10:08",
        "checkOutTime": "06-10-2023 19:28",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-11-03T11:20:50.996+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 10285,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-10-05"
        ],
        "appliedOnDate": "2023-10-31 16:08:42.997",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "05-10-2023 10:08",
        "checkOutTime": "05-10-2023 19:30",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-11-03T11:20:47.677+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 10284,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-10-04"
        ],
        "appliedOnDate": "2023-10-31 14:42:14.776",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "04-10-2023 10:11",
        "checkOutTime": "04-10-2023 19:30",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-11-03T11:20:44.38+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 10007,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-29"
        ],
        "appliedOnDate": "2023-09-30 19:31:51.128",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "29-09-2023 10:03",
        "checkOutTime": "29-09-2023 19:30",
        "regularizationReason": "2",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:39:52.596+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    }
]

export const batch2 = [
    {
        "regularizationRequestsId": 10005,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-27"
        ],
        "appliedOnDate": "2023-09-30 19:28:28.266",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "27-09-2023 10:09",
        "checkOutTime": "27-09-2023 19:10",
        "regularizationReason": "2",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:39:59.242+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 10004,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-26"
        ],
        "appliedOnDate": "2023-09-30 19:26:02.448",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "26-09-2023 10:03",
        "checkOutTime": "26-09-2023 19:10",
        "regularizationReason": "2",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:40:02.541+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 10003,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-25"
        ],
        "appliedOnDate": "2023-09-30 19:25:31.188",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "25-09-2023 10:03",
        "checkOutTime": "25-09-2023 19:14",
        "regularizationReason": "2",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:40:05.774+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 10002,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-22"
        ],
        "appliedOnDate": "2023-09-30 19:24:54.34",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "22-09-2023 10:04",
        "checkOutTime": "22-09-2023 19:13",
        "regularizationReason": "2",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:40:08.787+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 10001,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-21"
        ],
        "appliedOnDate": "2023-09-30 19:24:23.784",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "21-09-2023 10:04",
        "checkOutTime": "21-09-2023 19:08",
        "regularizationReason": "2",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:40:12.04+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 10000,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-20"
        ],
        "appliedOnDate": "2023-09-30 19:23:44.244",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "20-09-2023 10:04",
        "checkOutTime": "20-09-2023 19:13",
        "regularizationReason": "2",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:40:15.26+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 9999,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-19"
        ],
        "appliedOnDate": "2023-09-30 19:22:12.366",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "19-09-2023 10:01",
        "checkOutTime": "19-09-2023 19:14",
        "regularizationReason": "2",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:40:18.556+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 9998,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-18"
        ],
        "appliedOnDate": "2023-09-30 19:21:10.982",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "18-09-2023 10:18",
        "checkOutTime": "18-09-2023 19:21",
        "regularizationReason": "2",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:40:21.841+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 9996,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-15"
        ],
        "appliedOnDate": "2023-09-30 19:16:21.123",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "15-09-2023 10:10",
        "checkOutTime": "15-09-2023 19:16",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:40:28.377+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 9997,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-14"
        ],
        "appliedOnDate": "2023-09-30 19:17:25.886",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "14-09-2023 10:10",
        "checkOutTime": "14-09-2023 19:12",
        "regularizationReason": "2",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:40:25.111+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 9995,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-13"
        ],
        "appliedOnDate": "2023-09-30 19:15:22.07",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "13-09-2023 10:14",
        "checkOutTime": "13-09-2023 19:12",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:40:31.63+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 9994,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-12"
        ],
        "appliedOnDate": "2023-09-30 19:14:41.719",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "12-09-2023 10:08",
        "checkOutTime": "12-09-2023 19:12",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:40:34.869+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 9993,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-11"
        ],
        "appliedOnDate": "2023-09-30 19:14:06.342",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "11-09-2023 10:09",
        "checkOutTime": "11-09-2023 19:12",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:40:38.076+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 9992,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-09-01"
        ],
        "appliedOnDate": "2023-09-30 19:12:13.283",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "01-09-2023 10:11",
        "checkOutTime": "01-09-2023 19:12",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-10-04T10:40:41.179+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 9768,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-08-30"
        ],
        "appliedOnDate": "2023-09-02 16:08:02.427",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "30-08-2023 10:10",
        "checkOutTime": "30-08-2023 19:15",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-09-04T10:35:15.154+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 9767,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-08-28"
        ],
        "appliedOnDate": "2023-09-02 16:04:56.224",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "28-08-2023 10:15",
        "checkOutTime": "28-08-2023 19:20",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-09-04T10:35:21.778+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 9766,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-08-08"
        ],
        "appliedOnDate": "2023-09-02 16:01:21.596",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "08-08-2023 10:14",
        "checkOutTime": "08-08-2023 19:10",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-09-04T10:35:11.764+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 9765,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-08-07"
        ],
        "appliedOnDate": "2023-09-02 15:59:16.832",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "07-08-2023 10:10",
        "checkOutTime": "07-08-2023 19:15",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-09-04T10:35:08.529+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    },
    {
        "regularizationRequestsId": 9540,
        "empCode": "1282",
        "empName": "Aditya Gupta",
        "regularizationDate": [
            "2023-08-04"
        ],
        "appliedOnDate": "2023-08-18 10:48:55.628",
        "attendanceTemplate": "ProH2R Team Attendance Template",
        "requestType": "CHECKIN_AND_CHECKOUT",
        "checkInTime": "04-08-2023 10:02",
        "checkOutTime": "04-08-2023 19:10",
        "regularizationReason": "5",
        "regularizationComments": "Approve",
        "regularizationStatus": "APPROVED",
        "supervisorActionDate": "2023-09-04T10:35:18.378+05:30",
        "isHalfDay": null,
        "dayHalfs": null,
        "location": null,
        "band": null,
        "department": null,
        "designation": null,
        "shiftRecordId": 1,
        "primarySupervisorId": null,
        "secondarySupervisorId": null
    }
]